### PR TITLE
FIX: Low FPS dT Blowout

### LINKED ISSUE #60: Fix dT Blowout
when approaching low fps the smooth curve target approximation explodes with energy.
in gd gems 4 there is a nice article about this and maybe this can help to have a more fps independent smooth target approxmiation

### PR DESCRIPTION
**Pull request by callidaria**
closes #60

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -7,3 +7,4 @@ gmon.out
 core/include/*
 lib/*
 *.o
+texmex.jpg
```
Comment (callidaria) [inline .gitignore]: specific ignore for single test file is not good form

File: script/test.cpp [hunk 2]
```diff
@@ -8,7 +8,7 @@ TestScene::TestScene()
 {
 	// resources
 	vector<Texture*> __DudeTexture = {
-		g_Renderer.register_texture("./res/test/dude_colour.png",TEXTURE_FORMAT_SRGB),
+		g_Renderer.register_texture("./res/test/texmex.jpg",TEXTURE_FORMAT_SRGB),
```
Comment (callidaria) [inline script/test.cpp]: change to a location that will be explicitly excluded from version control

File: core/base.h [hunk 3]
```diff
@@ -234,13 +237,18 @@ inline f64 calculate_delta_time(std::chrono::steady_clock::time_point& t)
 }
 
 // math
-vec3 halfway(vec3 a,vec3 b);
+static inline u32 wrap_next(u32 x,u32 n) { x++;return x*(x<n); }
+static inline f32 fast_exp2(f32 x) { return 1.f/(1.f+x+.48f*x*x); }
+static inline f32 fast_exp3(f32 x) { return 1.f/(1.f+x+.48f*x*x+.235f*x*x*x); }
+static inline f32 angular_relationship(vec2 a,vec2 b) { return atan2(a.x*b.y-a.y*b.x,a.x*b.x+a.y*b.y); }
+static inline vec3 halfway(vec3 a,vec3 b) { return (a+b)*.5f; }
```
Comment (callidaria) [inline core/base.h]: create an issue to exclude the mathin' and physicsn' from the base and the system setup

**Review by callidaria — COMMENTED** [review]
revisions

**Review by callidaria — COMMENTED** [review]
approved
