### PR TITLE
Arbitrary Joint Transform

### LINKED ISSUE #10: Interpolate Between Animations
this i have never done. lets see how this goes. should in it's primal form be very achievable, but i see a million ways how this could go wrong.

### LINKED ISSUE #59: Manipulate Joint Targets
let the animation manipulate targets by joint target feature and also expose this to other features than animation, splitting animation iterator and in-between position interpolation

### LINKED ISSUE #64: Time Conversion
switch to intended time conversion by chrono.
it's pretty bad but right now it's somehow worse.

### PR DESCRIPTION
**Pull request by callidaria**
closes #59 
closes #64 
closes #10

### CODE REVIEW

File: core/renderer.cpp [hunk 1]
```diff
@@ -204,8 +204,66 @@ Mesh::Mesh(const char* path)
...
+void MeshJoint::request_position(const AnimKey<vec3>& target)
+{
+	prog_position = 0;
+	crr_position.key = ct_position;
+	crr_position.duration = 0;
+	target_position = target;
+}
+
+/**
+ *	TODO
```
Comment (callidaria) [inline core/renderer.cpp]: document

File: core/renderer.cpp [hunk 2]
```diff
@@ -204,8 +204,66 @@ Mesh::Mesh(const char* path)
...
+/**
+ * interpolate between joint transformation based on given data in struct
+ */
+void MeshJoint::interpolate()
+{
+	// time advancement
+	prog_position += g_Frame.delta_time;
+	prog_scale += g_Frame.delta_time;
+	prog_rotation += g_Frame.delta_time;
+	// TODO when target is reached, make the transition stop! (this is not applying to running animations)
```
Comment (callidaria) [inline core/renderer.cpp]: solve

File: core/renderer.cpp [hunk 3]
```diff
@@ -204,8 +204,66 @@ Mesh::Mesh(const char* path)
...
+
+	// calculate key progression
+	f32 dt_position = glm::clamp(prog_position/target_position.duration,.0,1.);
+	f32 dt_scale = glm::clamp(prog_scale/target_scale.duration,.0,1.);
+	f32 dt_rotation = glm::clamp(prog_rotation/target_rotation.duration,.0,1.);
```
Comment (callidaria) [inline core/renderer.cpp]: add a remark that this is slow and should be reviewed to allow for better performance (in-between calculation will always have unique inversions!)

File: core/renderer.cpp [hunk 4]
```diff
@@ -214,17 +272,32 @@ u16 _rc_get_joint_count(aiNode* root)
...
+	MeshJoint& __Joint = joints.back();
+
+	// extract transformation components
+	decompose(__Joint.transform,__Joint.ct_position,__Joint.ct_scale,__Joint.ct_rotation);
+	__Joint.crr_position.key = __Joint.ct_position;
+	__Joint.crr_scale.key = __Joint.ct_scale;
+	__Joint.crr_rotation.key = __Joint.ct_rotation;
+	__Joint.target_position.key = __Joint.ct_position;
+	__Joint.target_scale.key = __Joint.ct_scale;
+	__Joint.target_rotation.key = __Joint.ct_rotation;
```
Comment (callidaria) [inline core/renderer.cpp]: solve this together with the stopping after target has been reached. this is a terrible setup!
play around with it a little

File: core/renderer.cpp [hunk 5]
```diff
@@ -412,17 +500,29 @@ f64 AnimatedMesh::get_progress()
...
+template<typename T> AnimKey<T> _advance_keys(const vector<AnimKey<T>>& keys,f64 progress)
 {
-	while (durations[crr+1]<progress) crr++;
-	crr *= crr<durations.size()&&durations[crr]<progress;
-	u16 nxt = wrap_next(crr,durations.size());
-	return (progress-durations[crr])/((durations[nxt])-durations[crr]*(nxt>crr));
+	// find current key
+	u16 __Crr = 0;
+	while (keys[__Crr+1].duration<progress) __Crr++;
+	__Crr *= __Crr<keys.size()&&keys[__Crr].duration<progress;
```
Comment (callidaria) [inline core/renderer.cpp]: remove that doubled range guard somehow?

File: core/renderer.cpp [hunk 6]
```diff
@@ -433,48 +533,40 @@ void AnimatedMesh::update()
 		progress -= p_Animation.duration;
 		current_animation = standard_animation;
 	}
+	// TODO exchange rigid control structure with a usable one, then maybe change back to fmod solution
```
Comment (callidaria) [inline core/renderer.cpp:532]: this is a whole feature change. create an issue accordingly

File: core/renderer.cpp [hunk 7]
```diff
@@ -433,48 +533,40 @@ void AnimatedMesh::update()
...
+	// iterate joints for location animation transformations
+	for (MeshJoint& p_Joint : joints) p_Joint.interpolate();
 
 	// calculate transform after parent influence
 	mat4 __Parent = mat4(1.f);
 	_rc_transform_interpolation(joints[0],__Parent);
-	// FIXME it's unclear if joints[0] is always root node, this could lead to nasty consequences
 }
+// FIXME the switch to a separated update method has jambled up some vertices in the test mesh...
+// TODO while animate is requested, this should be default always-active for all registered anim meshes!
```
Comment (callidaria) [inline core/renderer.cpp]: this is absolutely crucial before merging! vital part of #59

File: core/renderer.h [hunk 8]
```diff
@@ -130,12 +158,29 @@ class Mesh
...
+	f32 prog_rotation = .0f;
+	vec3 ct_position;
+	vec3 ct_scale;
+	quat ct_rotation;
+	AnimKey<vec3> crr_position;
+	AnimKey<vec3> crr_scale;
+	AnimKey<quat> crr_rotation;
+	AnimKey<vec3> target_position;
+	AnimKey<vec3> target_scale;
+	AnimKey<quat> target_rotation;
```
Comment (callidaria) [inline core/renderer.h:183]: this seems very excessive! is all that really necessary?

File: core/renderer.h [hunk 9]
```diff
@@ -146,34 +191,13 @@ struct MeshJoint
...
-	f64 duration_inv;
-};
-
 class AnimatedMesh
 {
 public:
 	AnimatedMesh(const char* path);
 	void set_animation(u8 id);
 	f64 get_progress();
+	void animate();
```
Comment (callidaria) [inline core/renderer.h:200]: maybe this should be a switch-on/switch-off kind of thing so this does not have to be part of a script loop?

File: script/test.cpp [hunk 10]
```diff
@@ -192,8 +193,8 @@ void TestScene::update()
 
 	// player transformation
 	m_AnimationBatch->objects[m_DudeID].transform.reset();
-	m_AnimationBatch->objects[m_DudeID].transform.rotate_x(90.f);
 	m_AnimationBatch->objects[m_DudeID].transform.translate(-__CenteredPosition);
+	m_AnimationBatch->objects[m_DudeID].transform.rotate_x(90.f);
```
Comment (callidaria) [inline script/test.cpp:193]: weird change?

**Review by callidaria — COMMENTED** [review]
still loads of improvements

File: core/renderer.cpp (hunk 2 above)
Comment (callidaria) [reply core/renderer.cpp]: already solved by maximum of transition towards target

File: core/renderer.cpp [hunk 11]
```diff
@@ -433,48 +529,41 @@ void AnimatedMesh::update()
...
```
Comment (callidaria) [inline core/renderer.cpp]: those are outdated. remove both comments

**Review by callidaria — COMMENTED** [review]
remove comments

**Review by callidaria — COMMENTED** [review]
fine for now
